# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\"\n\x11\x41gentQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"&\n\x12\x41gentQueryResponse\x12\x10\n\x08response\x18\x01 \x01(\t2O\n\x0c\x41gentService\x12?\n\x08RunQuery\x12\x18.agent.AgentQueryRequest\x1a\x19.agent.AgentQueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTQUERYREQUEST']._serialized_start=22
  _globals['_AGENTQUERYREQUEST']._serialized_end=56
  _globals['_AGENTQUERYRESPONSE']._serialized_start=58
  _globals['_AGENTQUERYRESPONSE']._serialized_end=96
  _globals['_AGENTSERVICE']._serialized_start=98
  _globals['_AGENTSERVICE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
